repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.16
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.13.1-1
    hooks:
      - id: shfmt
        args: ["-i", "0", "-ci", "-ln", "bash", "-d"]
        files: ^PKGBUILD$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
    - id: mypy
      fail_fast: true
